name: 'TS Lint, Test, and Format'
on:
  pull_request:
  workflow_dispatch:

jobs:
  lint-test-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
      - run: npm run lint:fix
      - run: npm run tsc
      - run: npm run test
      - run: npm run fmt